### PR TITLE
Tutorial home

### LINKED ISSUE #22: Renaming `~/.rstudio` breaks running sessions
Shameema identified a problem where if a user attempted to run multiple tutorial-mode sessions at the same time the oldest sessions could crash. The reason for this was to create a clean environment I was renaming `~/.rstudio`. Doug suggested that since we are using Singularity to launch RStudio with a custom `/tmp` that we could change `$HOME` as well.

### PR DESCRIPTION
**Pull request by MorganRodgers**
Fixes #22.

### CODE REVIEW

File: template/script.sh.erb [hunk 1]
```diff
@@ -1,12 +1,25 @@
...
+%>
+
 # Load the required environment
 setup_env () {
   module purge
 
   # The rserver container module should set these environment variables:
 
-  #   SINGULARITY_BINDPATH="/usr/local,/etc/profile.d/lmod.sh,/usr/share/lmod,/opt/intel,/opt/mvapich2,/usr/lib64"
+  #   SINGULARITY_BINDPATH="/etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/users"
```
Comment (MorganRodgers) [inline template/script.sh.erb]: This comment on a good `SINGULARITY_BINDPATH` was out of date.

**Comment by johrstrom** [comment]
lgtm, I don't suppose folks will want, say their `~/.Renvron` _and_ these tutorial files? Either way, I guess we could still just prep the env in that `working_dir_host`.

**Comment by MorganRodgers** [comment]
Users might expect to have their regular environment. However, part of Shameema's specification for this tutorial mode is a clean environment; so no environment files, startup files, or pre-installed modules.
